// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {publicCode} from '../models';

export function AddFingerprint(arg1:publicCode.Fingerprint):Promise<Array<string>>;

export function AddPoc(arg1:publicCode.Poc):Promise<Array<string>>;

export function BackgroundImageSave(arg1:publicCode.Background):Promise<void>;

export function BackgroundSetting():Promise<string>;

export function BatchPocScan():Promise<publicCode.PocScanResult>;

export function DBInitialize():Promise<Array<string>>;

export function DefaultBrowserOpenUrl(arg1:string):Promise<void>;

export function DelFingerprint(arg1:Array<publicCode.Fingerprint>):Promise<Array<string>>;

export function DelFingerprintFile(arg1:Array<publicCode.Fingerprint>):Promise<Array<string>>;

export function DelPoc(arg1:Array<publicCode.Poc>):Promise<Array<string>>;

export function DelPocFile(arg1:Array<publicCode.Poc>):Promise<Array<string>>;

export function FSScan(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function FSScanClose():Promise<void>;

export function FSScanContinue():Promise<void>;

export function FSScanPause():Promise<void>;

export function FingerprintFileList(arg1:string):Promise<Array<publicCode.Fingerprint>>;

export function FingerprintGetName(arg1:string):Promise<Array<string>>;

export function FingerprintList(arg1:string):Promise<Array<publicCode.Fingerprint>>;

export function FingerprintLocalList(arg1:string):Promise<Array<publicCode.Fingerprint>>;

export function FingerprintScan():Promise<publicCode.FingerprintScanResult>;

export function FingerprintsDownload(arg1:Array<publicCode.Fingerprint>):Promise<Array<string>>;

export function FingerprintsUpload(arg1:Array<publicCode.Fingerprint>):Promise<Array<string>>;

export function LocalList(arg1:string):Promise<Array<publicCode.Poc>>;

export function PocExploitation(arg1:publicCode.Poc,arg2:string):Promise<void>;

export function PocList(arg1:string):Promise<Array<publicCode.Poc>>;

export function PocList2(arg1:string):Promise<Array<publicCode.Poc>>;

export function PocScan(arg1:Array<publicCode.Poc>,arg2:string):Promise<void>;

export function PocsDownload(arg1:Array<publicCode.Poc>):Promise<Array<string>>;

export function PocsUpload(arg1:Array<publicCode.Poc>):Promise<Array<string>>;

export function SaveSetting(arg1:publicCode.AllSetting,arg2:number):Promise<Array<string>>;

export function ScanBatch(arg1:string,arg2:Array<publicCode.Poc>):Promise<void>;

export function ScanClose():Promise<void>;

export function ScanContinue():Promise<void>;

export function ScanPause():Promise<void>;

export function ShowSetting():Promise<publicCode.AllSetting>;
