// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFingerprint(arg1) {
  return window['go']['main']['App']['AddFingerprint'](arg1);
}

export function AddPoc(arg1) {
  return window['go']['main']['App']['AddPoc'](arg1);
}

export function BackgroundImageSave(arg1) {
  return window['go']['main']['App']['BackgroundImageSave'](arg1);
}

export function BackgroundSetting() {
  return window['go']['main']['App']['BackgroundSetting']();
}

export function BatchPocScan() {
  return window['go']['main']['App']['BatchPocScan']();
}

export function DBInitialize() {
  return window['go']['main']['App']['DBInitialize']();
}

export function DefaultBrowserOpenUrl(arg1) {
  return window['go']['main']['App']['DefaultBrowserOpenUrl'](arg1);
}

export function DelFingerprint(arg1) {
  return window['go']['main']['App']['DelFingerprint'](arg1);
}

export function DelFingerprintFile(arg1) {
  return window['go']['main']['App']['DelFingerprintFile'](arg1);
}

export function DelPoc(arg1) {
  return window['go']['main']['App']['DelPoc'](arg1);
}

export function DelPocFile(arg1) {
  return window['go']['main']['App']['DelPocFile'](arg1);
}

export function FSScan(arg1, arg2, arg3) {
  return window['go']['main']['App']['FSScan'](arg1, arg2, arg3);
}

export function FSScanClose() {
  return window['go']['main']['App']['FSScanClose']();
}

export function FSScanContinue() {
  return window['go']['main']['App']['FSScanContinue']();
}

export function FSScanPause() {
  return window['go']['main']['App']['FSScanPause']();
}

export function FingerprintFileList(arg1) {
  return window['go']['main']['App']['FingerprintFileList'](arg1);
}

export function FingerprintGetName(arg1) {
  return window['go']['main']['App']['FingerprintGetName'](arg1);
}

export function FingerprintList(arg1) {
  return window['go']['main']['App']['FingerprintList'](arg1);
}

export function FingerprintLocalList(arg1) {
  return window['go']['main']['App']['FingerprintLocalList'](arg1);
}

export function FingerprintScan() {
  return window['go']['main']['App']['FingerprintScan']();
}

export function FingerprintsDownload(arg1) {
  return window['go']['main']['App']['FingerprintsDownload'](arg1);
}

export function FingerprintsUpload(arg1) {
  return window['go']['main']['App']['FingerprintsUpload'](arg1);
}

export function LocalList(arg1) {
  return window['go']['main']['App']['LocalList'](arg1);
}

export function PocExploitation(arg1, arg2) {
  return window['go']['main']['App']['PocExploitation'](arg1, arg2);
}

export function PocList(arg1) {
  return window['go']['main']['App']['PocList'](arg1);
}

export function PocList2(arg1) {
  return window['go']['main']['App']['PocList2'](arg1);
}

export function PocScan(arg1, arg2) {
  return window['go']['main']['App']['PocScan'](arg1, arg2);
}

export function PocsDownload(arg1) {
  return window['go']['main']['App']['PocsDownload'](arg1);
}

export function PocsUpload(arg1) {
  return window['go']['main']['App']['PocsUpload'](arg1);
}

export function SaveSetting(arg1, arg2) {
  return window['go']['main']['App']['SaveSetting'](arg1, arg2);
}

export function ScanBatch(arg1, arg2) {
  return window['go']['main']['App']['ScanBatch'](arg1, arg2);
}

export function ScanClose() {
  return window['go']['main']['App']['ScanClose']();
}

export function ScanContinue() {
  return window['go']['main']['App']['ScanContinue']();
}

export function ScanPause() {
  return window['go']['main']['App']['ScanPause']();
}

export function ShowSetting() {
  return window['go']['main']['App']['ShowSetting']();
}
